/* This is file is automatically generated */
#define BUILD_ARCH "linuxx8664gcc"
#define BUILD_NODE "Linux lcgapp-cc7-x86-64-16.cern.ch 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"
#define CXX "c++"
#define COMPILER "/usr/bin/c++"
#define COMPILERVERS "c++"
#define MAKESHAREDLIB  "cd $BuildDir ; c++ -c $Opt -pipe -m64 -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations $IncludePath $SourceFiles ; c++ $ObjectFiles -shared  $LinkedLibs -o $SharedLib"
#define MAKEEXE "cd $BuildDir ; c++ -c  -pipe -m64 -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations $IncludePath $SourceFiles; c++ $ObjectFiles  -o $ExeName $LinkedLibs -lm -ldl -lpthread -rdynamic"
#define CXXOPT "-O2 -DNDEBUG"
#define CXXDEBUG "-g  -fno-reorder-blocks -fno-schedule-insns -fno-inline"
#define ROOTBUILD ""
#define LINKEDLIBS "-L$ROOTSYS/lib -lCore -lRint "
#define INCLUDEPATH "-I$ROOTSYS/include"
#define OBJEXT "o"
#define SOEXT "so"
